# Generated by Django 3.0.7 on 2020-08-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
