# Generated by Django 3.0.7 on 2020-08-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenApp', '0002_auto_20200822_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.PositiveIntegerField(blank=True, max_length=100),
        ),
    ]
