# Generated by Django 3.0.7 on 2020-08-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenApp', '0004_auto_20200822_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
