# Generated by Django 3.0.7 on 2020-08-28 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenApp', '0019_auto_20200826_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
