# Generated by Django 3.0.7 on 2020-08-31 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenApp', '0021_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='digital',
            new_name='ship',
        ),
    ]
