# Generated by Django 3.0.7 on 2020-09-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenApp', '0023_customer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile',
            field=models.ImageField(blank=True, default='img/icon.svg.png', null=True, upload_to='profile'),
        ),
    ]
