# Generated by Django 3.0.7 on 2020-09-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenApp', '0031_auto_20200901_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile',
            field=models.ImageField(blank=True, default='profile/logo.png', null=True, upload_to='profile'),
        ),
    ]
