# Generated by Django 3.1.7 on 2021-06-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenApp', '0034_auto_20200902_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('V', 'Vegitable'), ('F', 'Fruit')], max_length=2, null=True),
        ),
    ]
